version: '2'

services:
  ctfgame0_db:
    image: mysql:5.7
    volumes:
      - "./dckr_mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KzhyntJxwt
      MYSQL_DATABASE: fhqjuryad
      MYSQL_USER: fhqjuryad
      MYSQL_PASSWORD: uW2r0V5kpK
    networks:
      - ctf0

  ctfgame0_jury:
    depends_on:
      - ctfgame0_db
    image: ctfgame0/fhq-jury-ad:0.1.0
    volumes:
      - "./jury.d:/usr/share/fhq-jury-ad/jury.d"
    ports:
      - "8080:8080"
    restart: always
    links:
      - "ctfgame0_db"
    networks:
      - ctf0

networks:
  ctf0:
    driver: bridge
